exports.CATEGORIES = [
    "electronics",
    "bag",
    "camera",
    "computers",
    "office",
    "food",
    "beverage",
    "alcohol",
    "sports",
    "outdoors",
    "clothing",
    "shoes",
    "jewelry",
    "peripherals",
];